SELECT
  *
FROM
  "BRIGHTCOFFEE"."COFFEE_STORE"."COFFEE_SALES";

SELECT
  MIN (transaction_time) AS Opening_time, MAX (transaction_time) AS Closing_time,
FROM
  "BRIGHTCOFFEE"."COFFEE_STORE"."COFFEE_SALES";

SELECT
  DISTINCT UNIT_PRICE,
FROM
  "BRIGHTCOFFEE"."COFFEE_STORE"."COFFEE_SALES"
ORDER BY UNIT_PRICE ASC;

SELECT
  SUM (TRANSACTION_QTY) AS TOTAL_QTY
FROM
  "BRIGHTCOFFEE"."COFFEE_STORE"."COFFEE_SALES";

SELECT

--COUNTS
  COUNT (DISTINCT TRANSACTION_ID) AS Number_of_purchases,
  COUNT (DISTINCT PRODUCT_ID) AS Number_of_products,
  COUNT (DISTINCT STORE_ID) AS Number_of_stores,

--CATS
  STORE_LOCATION,
  PRODUCT_CATEGORY,
  PRODUCT_DETAIL,
  PRODUCT_TYPE,

--DATES
  TO_DATE (TRANSACTION_DATE) AS Purchase_date,
  DAYOFMONTH (TO_DATE(TRANSACTION_DATE)) AS Day_of_month,
  DAYNAME (TO_DATE(TRANSACTION_DATE)) AS Day_name,
  MONTHNAME(TO_DATE(TRANSACTION_DATE)) AS Month_name,
  TO_CHAR (TO_DATE(TRANSACTION_DATE),'YYYYMM') AS Month_ID,

--TIME
CASE
    WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'Morning'
    WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'Afternoon'
    ELSE 'Evening'
END AS TIME_BUCKETS,

-- WEEKDAY/WEEKEND
CASE
    WHEN Day_name NOT IN ('Sat','Sun') THEN 'Weekday'
    ELSE 'Weekend'
END AS Day_buckets,

--REVENUE
ROUND(SUM(IFNULL(TRANSACTION_QTY,0)*IFNULL(UNIT_PRICE,0)),0) AS Revenue,

FROM
  "BRIGHTCOFFEE"."COFFEE_STORE"."COFFEE_SALES"
GROUP BY ALL;
  
